---
name: cd-workflow
on:
  workflow_run:
    workflows: [ci-workflow]
    branches: [main]
env:
  PACKAGE_PATH: "./publish"

jobs:
  cd:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}