---
name: CD Workflow
on:
  workflow_run:
    workflows:
    - "CI Workflow"
    types: [completed]
    branches:
    - "main"

env:
  APP_SERVICE_NAME: "app-${{ vars.APPLICATION_NAME }}-${{ vars.ENVIRONMENT }}"
  RESOURCE_GROUP_NAME: 
    "rg-${{ vars.APPLICATION_NAME }}-${{ vars.ENVIRONMENT }}-${{ vars.LOCATION }}"
  PACKAGE_PATH: "./publish"

jobs:
  cd:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:

      - name: Download Artifact from GitHub
        uses: dawidd6/action-download-artifact@v2
        with:
          run_id: ${{ github.event.workflow_run.id }}
          name: ${{ vars.APPLICATION_NAME }}-release
          path: ${{ env.PACKAGE_PATH }}

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}          

      - name: Get App Service Publish Profile
        id: get-publish-profile
        uses: azure/CLI@v1.0.7
        with:
          inlineScript: |
            echo APP_SERVICE_PUBLISH_PROFILE = $(az webapp deployment list-publishing-profiles --name ${{ env.APP_SERVICE_NAME }} --resource-group ${{ env.RESOURCE_GROUP_NAME }} --subscription ${{ vars.SUBSCRIPTION_NAME }} --xml)  >> $GITHUB_ENV

      - name: Deploy to Dev
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.APP_SERVICE_NAME }}
          publish-profile: ${{ steps.get-publish-profile.outputs.APP_SERVICE_PUBLIC_PROFILE }}
          package: ${{ env.PACKAGE_PATH }}
          # slot-name: "staging"
          images:
