name: Publish
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "7.0.x"

      - name: Restore
        run: dotnet restore ./GitHubActionsDemo.sln

      - name: Build
        run: dotnet build ./GitHubActionsDemo.sln --configuration release --no-restore

      - name: Test
        run: dotnet test --no-restore --logger trx --results-directory "TestResults"

      - name: Upload Test Results
        uses: actions/upload-artifact@v3
        with:
          name: TestResults
          path: TestResults
        if: always()

      - name: Generate Coverage Report
        run: |
          cd ./tests/GitHubActionsDemo.WebApi.Tests/
          dotnet test /p:CollectCoverage=true /p:CoverletOutput=TestResults/ /p:CoverletOutputFormat=lcov

      - name: Publish Coverage Report to coveralls.io
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.COVERALLS_TOKEN }}
          path-to-lcov: ${{ github.workspace }}/tests/GitHubActionsDemo.WebApi.Tests/TestResults/coverage.info

      - name: Publish
        run: dotnet publish ./GitHubActionsDemo.sln --configuration release --no-build
#   create-azure-infrastructure:
#     runs-on: ubuntu-latest

#     steps:
#       - uses: actions/checkout@v3

#       - name: Test
#         run: dotnet test --no-restore --logger trx --results-directory "TestResults"
